# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar
        #
    assets:
        stylesheets:
            inputs:
            #CSS Global Compulsory
                - bundles/adesite/css/main.css
                - bundles/adesite/css/home.css
                - bundles/adesite/css/bjqs.css
                - bundles/adesite/css/demo.css
            filters: [?yui_css, cssrewrite]

        javascripts_header:
            inputs:
                #JS Global Compulsory
                - bundles/adesite/js/jquery-1.8.2.min.js
                - bundles/adesite/js/bjqs-1.3.min.js
                - bundles/adesite/js/libs/jquery.secret-source.min.js
            filters: [?yui_js, cssrewrite]