parameters:
#    ade_site.example.class: ADE\SiteBundle\Example

services:
#    ade_site.example:
#        class: %ade_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
